# Generated by Django 3.2.6 on 2021-08-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
                ('horario_1', models.CharField(max_length=250)),
                ('horario_2', models.CharField(blank=True, max_length=250, null=True)),
                ('correo', models.EmailField(max_length=254)),
            ],
            options={
                'verbose_name': '4. Contacto',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=250)),
                ('descripcion', models.TextField()),
            ],
            options={
                'verbose_name': '3. Servicios',
                'verbose_name_plural': '3. Servicios',
            },
        ),
    ]
