# Generated by Django 3.2.6 on 2021-08-30 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0003_auto_20210825_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='telefono_consultorio',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
