# Generated by Django 3.2.6 on 2021-08-25 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('edad', models.IntegerField()),
                ('sexo', models.CharField(choices=[('Femenino', 'Femenino'), ('Masculino', 'Masculino')], max_length=10)),
                ('telefono', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('app', models.TextField(verbose_name='Antecedentes personales patológicos')),
                ('apf', models.TextField(verbose_name='Antecedentes familiares')),
                ('fecha_ingreso', models.DateField(auto_now_add=True, verbose_name='Fecha de ingreso al sistema')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_consulta', models.DateField()),
                ('motivo_consulta', models.TextField()),
                ('hea', models.TextField(verbose_name='Historial de enfermedades actuales')),
                ('exfx', models.TextField(verbose_name='Examen físico')),
                ('dx', models.TextField(verbose_name='Diagnóstico')),
                ('tx', models.TextField(verbose_name='Tratamiento')),
                ('fecha_prox_consulta', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='resumenes_clinicos.paciente')),
            ],
        ),
    ]
